name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 如果是 npm 项目需要构建，非 npm 项目可删除这部分
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build  # 执行构建命令
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 对于 npm 项目，通常是 dist 目录；纯静态文件直接用 .
          publish_dir: ./dist  # 替换为你的构建输出目录